# Numpy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.


conda install numpy 
pip install numpy

Numpy is also incredibly fast, as it has bindings to C libraries

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

Cover toplics:

* np.array
* np.arange(start,end,stepsize)
* np.zeros(count)
* np.ones(count)
* np.linspace(start,end,spacepoint)
* np.eye(count) //diagnols of ones
* np.random.rand(count) //uniform distrubution
* np.random.randn(count) // Gaussian distribution]
* np.random.randint(start,end,count)
* arr.shape
* arr.reshape(2,2)
* arr.max()
* arr.argmax()
* arr.dtype







In [1]:
_list = [1,2,3,4,5,6,7]

In [2]:
 import numpy as np

In [3]:
arr = np.array(_list)

In [4]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
_list = [[1,2,3],[4,5,6],[8,3,2]]

In [6]:
arr = np.array(_list)

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [8, 3, 2]])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#third param is step size
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,1,80)

array([0.        , 0.01265823, 0.02531646, 0.03797468, 0.05063291,
       0.06329114, 0.07594937, 0.08860759, 0.10126582, 0.11392405,
       0.12658228, 0.13924051, 0.15189873, 0.16455696, 0.17721519,
       0.18987342, 0.20253165, 0.21518987, 0.2278481 , 0.24050633,
       0.25316456, 0.26582278, 0.27848101, 0.29113924, 0.30379747,
       0.3164557 , 0.32911392, 0.34177215, 0.35443038, 0.36708861,
       0.37974684, 0.39240506, 0.40506329, 0.41772152, 0.43037975,
       0.44303797, 0.4556962 , 0.46835443, 0.48101266, 0.49367089,
       0.50632911, 0.51898734, 0.53164557, 0.5443038 , 0.55696203,
       0.56962025, 0.58227848, 0.59493671, 0.60759494, 0.62025316,
       0.63291139, 0.64556962, 0.65822785, 0.67088608, 0.6835443 ,
       0.69620253, 0.70886076, 0.72151899, 0.73417722, 0.74683544,
       0.75949367, 0.7721519 , 0.78481013, 0.79746835, 0.81012658,
       0.82278481, 0.83544304, 0.84810127, 0.86075949, 0.87341772,
       0.88607595, 0.89873418, 0.91139241, 0.92405063, 0.93670

In [15]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
# its default is between 0,1
# uniform distribution
np.random.rand(4)

array([0.22143321, 0.40448652, 0.80846589, 0.41432331])

In [17]:
np.random.rand(4,5)

array([[0.69070769, 0.35288262, 0.20140156, 0.8904328 , 0.11553561],
       [0.55797838, 0.76943611, 0.00401007, 0.17431449, 0.37616698],
       [0.24484281, 0.96666051, 0.60962209, 0.13171385, 0.10057438],
       [0.5541841 , 0.26170368, 0.54019859, 0.15729757, 0.52188064]])

In [18]:
# Normal distribution, also known as the Gaussian distribution
np.random.randn(4)

array([-0.6177929 , -1.25748859, -2.07970764, -0.03609292])

In [19]:
np.random.randn(4,5)

array([[ 0.69789382, -1.2465013 ,  1.17901675,  0.1657883 ,  0.51392474],
       [-0.42573149,  1.39261506,  0.93499075, -1.53086592, -0.79498955],
       [ 0.35058669,  0.52535497, -0.38696735,  0.19571883, -1.26059211],
       [ 1.51269744, -0.81690238,  0.47157802,  1.25909658,  1.60331922]])

In [20]:
np.random.randint(0,100,40)

array([78, 20, 68, 58, 65, 61, 37, 43, 11, 30,  8, 31, 44, 23, 38, 64, 89,
       95, 58, 36,  7, 63, 29,  9, 57, 22, 29, 41, 12, 42, 20, 43, 52, 52,
       99, 57, 39, 16, 17, 10])

In [21]:
randomArray = np.random.randn(10,2)

In [22]:
randomArray


array([[-0.95877073, -2.26547785],
       [-0.44804192, -0.4667143 ],
       [-0.37110581,  1.77398327],
       [-0.82007712,  2.08916046],
       [ 0.99362305,  1.09443321],
       [-0.64298399,  0.14825039],
       [-1.41870629, -2.02941361],
       [ 0.75869461, -1.60739679],
       [-1.04767542, -0.04110562],
       [-0.13945136, -0.56898807]])

In [23]:
randomArray.reshape(4,5)

array([[-0.95877073, -2.26547785, -0.44804192, -0.4667143 , -0.37110581],
       [ 1.77398327, -0.82007712,  2.08916046,  0.99362305,  1.09443321],
       [-0.64298399,  0.14825039, -1.41870629, -2.02941361,  0.75869461],
       [-1.60739679, -1.04767542, -0.04110562, -0.13945136, -0.56898807]])

In [24]:
randomArray.reshape(5,4)

array([[-0.95877073, -2.26547785, -0.44804192, -0.4667143 ],
       [-0.37110581,  1.77398327, -0.82007712,  2.08916046],
       [ 0.99362305,  1.09443321, -0.64298399,  0.14825039],
       [-1.41870629, -2.02941361,  0.75869461, -1.60739679],
       [-1.04767542, -0.04110562, -0.13945136, -0.56898807]])

In [25]:
randomArray.shape

(10, 2)

In [26]:
randomArray = randomArray.reshape(4,5)

In [27]:
randomArray

array([[-0.95877073, -2.26547785, -0.44804192, -0.4667143 , -0.37110581],
       [ 1.77398327, -0.82007712,  2.08916046,  0.99362305,  1.09443321],
       [-0.64298399,  0.14825039, -1.41870629, -2.02941361,  0.75869461],
       [-1.60739679, -1.04767542, -0.04110562, -0.13945136, -0.56898807]])

In [28]:
randomArray.shape


(4, 5)

In [29]:
randomArray.max()

2.089160455386657

In [30]:
randomArray.argmax()

7

In [31]:
randomArray.min()

-2.2654778462996976

In [32]:
randomArray.argmin

<function ndarray.argmin>

In [67]:
randomArray.dtype

dtype('float64')