In [1]:
import numpy as np

# NumPy Indexing and Selection

In [2]:
_array = np.arange(11,21)

In [3]:
_array 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
_array[8]

19

# Bracket Indexing and Selection

In [5]:
_array[1:4]

array([12, 13, 14])

In [6]:
_array[:8]

array([11, 12, 13, 14, 15, 16, 17, 18])

# Broadcasting

In [10]:
# numpy array just like python list,howver in numpy we can do broadcast

In [11]:
_array[:4] = 999

In [12]:
_array

array([999, 999, 999, 999,  15,  16,  17,  18,  19,  20])

In [13]:
 _arr_cpy = _array.copy()

In [14]:
_arr_cpy

array([999, 999, 999, 999,  15,  16,  17,  18,  19,  20])

# indexing and selection arrays

In [15]:
_2d = np.array([[3,56,76,90],[234,56,78,0],[23,56,789,90]])

In [16]:
_2d

array([[  3,  56,  76,  90],
       [234,  56,  78,   0],
       [ 23,  56, 789,  90]])

In [17]:
_2d[0][3]

90

In [18]:
_2d[1]

array([234,  56,  78,   0])

In [19]:
_2d[0,3]

90

In [27]:
_2d[:][2:]

array([[ 23,  56, 789,  90]])

In [29]:
_2d[:2,2:]

array([[76, 90],
       [78,  0]])

In [30]:
_2d > 10

array([[False,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [31]:
_bool = _2d > 10

In [32]:
_bool

array([[False,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True]])

In [33]:
_2d[_bool]

array([ 56,  76,  90, 234,  56,  78,  23,  56, 789,  90])

In [34]:
_2d[_2d > 30]

array([ 56,  76,  90, 234,  56,  78,  56, 789,  90])